package au.com.entitysolutions.taskflows.train.model.client;

import au.com.entitysolutions.taskflows.train.model.common.CommonTrainTFAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 15:35:43 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommonTrainTFAppModuleClient extends ApplicationModuleImpl implements CommonTrainTFAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public CommonTrainTFAppModuleClient() {
    }


    public BlobDomain downloadDoc(String userTFId, String stepName,
                                  String documentType,
                                  String documentSubType) {
        Object _ret =
            this.riInvokeExportedMethod(this,"downloadDoc",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userTFId, stepName, documentType, documentSubType});
        return (BlobDomain)_ret;
    }

    public void completeStep(String userTFId, String stepName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"completeStep",new String [] {"java.lang.String","java.lang.String"},new Object[] {userTFId, stepName});
        return;
    }

    public Number uploadDoc(String userTFId, String stepName, String docName,
                            BlobDomain fileContent, String fileMime,
                            String fileLength, String fileName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"uploadDoc",new String [] {"java.lang.String","java.lang.String","java.lang.String","oracle.jbo.domain.BlobDomain","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userTFId, stepName, docName, fileContent, fileMime, fileLength, fileName});
        return (Number)_ret;
    }

    public Number removeDoc(String userTFId, String stepName, String docName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"removeDoc",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {userTFId, stepName, docName});
        return (Number)_ret;
    }
}
