package au.com.entitysolutions.taskflows.train.model.client;

import au.com.entitysolutions.taskflows.system.model.client.PortalCommonAppModuleClient;
import au.com.entitysolutions.taskflows.train.model.common.TrainAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 11:22:25 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrainAppModuleClient extends PortalCommonAppModuleClient implements TrainAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public TrainAppModuleClient() {
    }

    public void startTaskflow(String userTFId, String userName,
                              String ipAddress) {
        Object _ret =
            this.riInvokeExportedMethod(this,"startTaskflow",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {userTFId, userName, ipAddress});
        return;
    }
}
