package au.com.entitysolutions.taskflows.train.signup.model.client;

import au.com.entitysolutions.taskflows.train.model.client.CommonTrainTFAppModuleClient;
import au.com.entitysolutions.taskflows.train.signup.model.common.IProSignUpTrainAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 13:09:54 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IProSignUpTrainAppModuleClient extends CommonTrainTFAppModuleClient implements IProSignUpTrainAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public IProSignUpTrainAppModuleClient() {
    }


    public void createEmptySecondaryBankRecords() {
        Object _ret =
            this.riInvokeExportedMethod(this,"createEmptySecondaryBankRecords",null,null);
        return;
    }

    public void resetPrimaryAccountPriority() {
        Object _ret =
            this.riInvokeExportedMethod(this,"resetPrimaryAccountPriority",null,null);
        return;
    }

    public void resetSuperDetails() {
        Object _ret =
            this.riInvokeExportedMethod(this,"resetSuperDetails",null,null);
        return;
    }

    public void resetSuperFundType() {
        Object _ret =
            this.riInvokeExportedMethod(this,"resetSuperFundType",null,null);
        return;
    }

    public void completeTaskFlow(String userTFId, String welcomeStepName,
                                 String reviewStepName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"completeTaskFlow",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {userTFId, welcomeStepName, reviewStepName});
        return;
    }

    public void setICContractLookup() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setICContractLookup",null,null);
        return;
    }
}
