package au.com.entitysolutions.taskflows.system.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 04 15:17:19 EST 2011
// ---------------------------------------------------------------------
public interface PortalCommonAppModule extends ApplicationModule {

  void emailFileUploader(String attachmentPath, String fileDetails);

  String sendEmailWithAttachments(String to, String cc, String bcc,
                                  String subject, String body,
                                  String attachmentPath);
}
