package au.com.entitysolutions.taskflows.system.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 04 11:01:34 EST 2011
// ---------------------------------------------------------------------
public interface SharedAppModule extends ApplicationModule {
    String getGlobalVariable(String globalVariable);
}
