<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="../businessCatalog/Expenses/ExpensesToFileObject.xsd"/>
      <rootElement name="ExpensesToFileObject" namespace="http://xmlns.oracle.com/bpm/bpmobject/Expenses/ExpensesToFileObject"/>
      <param name="processExpensesToFileDataObj" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="../businessCatalog/Expenses/ExpensesToHumanTaskflow.xsd"/>
      <rootElement name="ExpensesToHumanTaskflow" namespace="http://xmlns.oracle.com/bpm/bpmobject/Expenses/ExpensesToHumanTaskflow"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [MON JUN 03 18:06:07 EST 2013]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:bpmo="http://xmlns.oracle.com/bpm/bpmobject/"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns1="http://xmlns.oracle.com/bpm/bpmobject/Expenses/ExpensesToHumanTaskflow"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:ns0="http://xmlns.oracle.com/bpm/bpmobject/Expenses/ExpensesToFileObject"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl bpmo ns0 xsd ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <ns1:ExpensesToHumanTaskflow>
      <ns1:ht_amount>
        <xsl:value-of select="/ns0:ExpensesToFileObject/ns0:amount"/>
      </ns1:ht_amount>
      <ns1:ht_description>
        <xsl:value-of select="/ns0:ExpensesToFileObject/ns0:user_id"/>
      </ns1:ht_description>
      <ns1:ht_input1>
        <xsl:value-of select="/ns0:ExpensesToFileObject/ns0:entry_id"/>
      </ns1:ht_input1>
    </ns1:ExpensesToHumanTaskflow>
  </xsl:template>
</xsl:stylesheet>
