package au.com.entitysolutions.taskflows.login.model.common;

import au.com.entitysolutions.taskflows.system.model.common.PortalCommonAppModule;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 04 13:48:42 EST 2011
// ---------------------------------------------------------------------
public interface LoginAppModule extends PortalCommonAppModule {

    Boolean sendUserId(String emailAddress, String ipAddress);

    Boolean resetPassword(String emailAddress, String ipAddress);

    Boolean acceptTAndC(String userName, String ipAddress);

    Boolean changePassword(String userName, String ipAddress,
                           String oldPassword, String newPassword);

    Boolean validatePasswordRules(String userName, String oldPassword,
                                  String newPassword);

    Boolean updateSysPrimaryEmail(String userName,String email);
}
