package au.com.entitysolutions.taskflows.train.signup.model;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 15 11:26:13 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortalSignupSecondaryBankDetailsViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BankDetailsId {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getBankDetailsId();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setBankDetailsId((Number)value);
            }
        }
        ,
        UserTfId {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getUserTfId();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setUserTfId((Number)value);
            }
        }
        ,
        AmountUnit {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getAmountUnit();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAmountUnit((String)value);
            }
        }
        ,
        Amount {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getAmount();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAmount((String)value);
            }
        }
        ,
        BankName {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getBankName();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setBankName((String)value);
            }
        }
        ,
        Bsb {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getBsb();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setBsb((String)value);
            }
        }
        ,
        AccountNo {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getAccountNo();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAccountNo((String)value);
            }
        }
        ,
        AccountName {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getAccountName();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAccountName((String)value);
            }
        }
        ,
        Transformed {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getTransformed();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setTransformed((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        Priority {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getPriority();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setPriority((BigDecimal)value);
            }
        }
        ,
        AmountDollar {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getAmountDollar();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAmountDollar((String)value);
            }
        }
        ,
        AmountPercentage {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getAmountPercentage();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAmountPercentage((String)value);
            }
        }
        ,
        PortalSignupPersonalDetailsView {
            public Object get(PortalSignupSecondaryBankDetailsViewRowImpl obj) {
                return obj.getPortalSignupPersonalDetailsView();
            }

            public void put(PortalSignupSecondaryBankDetailsViewRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PortalSignupSecondaryBankDetailsViewRowImpl object);

        public abstract void put(PortalSignupSecondaryBankDetailsViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BANKDETAILSID = AttributesEnum.BankDetailsId.index();
    public static final int USERTFID = AttributesEnum.UserTfId.index();
    public static final int AMOUNTUNIT = AttributesEnum.AmountUnit.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int BANKNAME = AttributesEnum.BankName.index();
    public static final int BSB = AttributesEnum.Bsb.index();
    public static final int ACCOUNTNO = AttributesEnum.AccountNo.index();
    public static final int ACCOUNTNAME = AttributesEnum.AccountName.index();
    public static final int TRANSFORMED = AttributesEnum.Transformed.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int PRIORITY = AttributesEnum.Priority.index();
    public static final int AMOUNTDOLLAR = AttributesEnum.AmountDollar.index();
    public static final int AMOUNTPERCENTAGE = AttributesEnum.AmountPercentage.index();
    public static final int PORTALSIGNUPPERSONALDETAILSVIEW = AttributesEnum.PortalSignupPersonalDetailsView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PortalSignupSecondaryBankDetailsViewRowImpl() {
    }

    /**
     * Gets PortalSignupBankDetails entity object.
     * @return the PortalSignupBankDetails
     */
    public PortalSignupBankDetailsImpl getPortalSignupBankDetails() {
        return (PortalSignupBankDetailsImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for BANK_DETAILS_ID using the alias name BankDetailsId.
     * @return the BANK_DETAILS_ID
     */
    public Number getBankDetailsId() {
        return (Number) getAttributeInternal(BANKDETAILSID);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_DETAILS_ID using the alias name BankDetailsId.
     * @param value value to set the BANK_DETAILS_ID
     */
    public void setBankDetailsId(Number value) {
        setAttributeInternal(BANKDETAILSID, value);
    }

    /**
     * Gets the attribute value for USER_TF_ID using the alias name UserTfId.
     * @return the USER_TF_ID
     */
    public Number getUserTfId() {
        return (Number) getAttributeInternal(USERTFID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_TF_ID using the alias name UserTfId.
     * @param value value to set the USER_TF_ID
     */
    public void setUserTfId(Number value) {
        setAttributeInternal(USERTFID, value);
    }

    /**
     * Gets the attribute value for AMOUNT_UNIT using the alias name AmountUnit.
     * @return the AMOUNT_UNIT
     */
    public String getAmountUnit() {
        return (String) getAttributeInternal(AMOUNTUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT_UNIT using the alias name AmountUnit.
     * @param value value to set the AMOUNT_UNIT
     */
    public void setAmountUnit(String value) {
        setAttributeInternal(AMOUNTUNIT, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public String getAmount() {
        return (String) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(String value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for BANK_NAME using the alias name BankName.
     * @return the BANK_NAME
     */
    public String getBankName() {
        return (String) getAttributeInternal(BANKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BANK_NAME using the alias name BankName.
     * @param value value to set the BANK_NAME
     */
    public void setBankName(String value) {
        setAttributeInternal(BANKNAME, value);
    }

    /**
     * Gets the attribute value for BSB using the alias name Bsb.
     * @return the BSB
     */
    public String getBsb() {
        return (String) getAttributeInternal(BSB);
    }

    /**
     * Sets <code>value</code> as attribute value for BSB using the alias name Bsb.
     * @param value value to set the BSB
     */
    public void setBsb(String value) {
        setAttributeInternal(BSB, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_NO using the alias name AccountNo.
     * @return the ACCOUNT_NO
     */
    public String getAccountNo() {
        return (String) getAttributeInternal(ACCOUNTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_NO using the alias name AccountNo.
     * @param value value to set the ACCOUNT_NO
     */
    public void setAccountNo(String value) {
        setAttributeInternal(ACCOUNTNO, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_NAME using the alias name AccountName.
     * @return the ACCOUNT_NAME
     */
    public String getAccountName() {
        return (String) getAttributeInternal(ACCOUNTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_NAME using the alias name AccountName.
     * @param value value to set the ACCOUNT_NAME
     */
    public void setAccountName(String value) {
        setAttributeInternal(ACCOUNTNAME, value);
    }

    /**
     * Gets the attribute value for TRANSFORMED using the alias name Transformed.
     * @return the TRANSFORMED
     */
    public String getTransformed() {
        return (String) getAttributeInternal(TRANSFORMED);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFORMED using the alias name Transformed.
     * @param value value to set the TRANSFORMED
     */
    public void setTransformed(String value) {
        setAttributeInternal(TRANSFORMED, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for PRIORITY using the alias name Priority.
     * @return the PRIORITY
     */
    public BigDecimal getPriority() {
        return (BigDecimal) getAttributeInternal(PRIORITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIORITY using the alias name Priority.
     * @param value value to set the PRIORITY
     */
    public void setPriority(BigDecimal value) {
        setAttributeInternal(PRIORITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AmountDollar.
     * @return the AmountDollar
     */
    public String getAmountDollar() {
        return (String) getAttributeInternal(AMOUNTDOLLAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AmountDollar.
     * @param value value to set the  AmountDollar
     */
    public void setAmountDollar(String value) {        
        if("A".equals(this.getAmountUnit())) {            
            setAttributeInternal(AMOUNT, value);
        }
        setAttributeInternal(AMOUNTDOLLAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AmountPercentage.
     * @return the AmountPercentage
     */
    public String getAmountPercentage() {
        return (String) getAttributeInternal(AMOUNTPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AmountPercentage.
     * @param value value to set the  AmountPercentage
     */
    public void setAmountPercentage(String value) {       
        if("P".equals(this.getAmountUnit())) {
            setAttributeInternal(AMOUNT, value);
        }
        setAttributeInternal(AMOUNTPERCENTAGE, value);
    }


    /**
     * Gets the associated <code>Row</code> using master-detail link PortalSignupPersonalDetailsView.
     */
    public Row getPortalSignupPersonalDetailsView() {
        return (Row)getAttributeInternal(PORTALSIGNUPPERSONALDETAILSVIEW);
    }

    /**
     * Sets the master-detail link PortalSignupPersonalDetailsView between this object and <code>value</code>.
     */
    public void setPortalSignupPersonalDetailsView(Row value) {
        setAttributeInternal(PORTALSIGNUPPERSONALDETAILSVIEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
