package au.com.entitysolutions.taskflows.train.model;

import au.com.entitysolutions.taskflows.model.CustomEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 27 10:32:40 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PortalUserTFStepImpl extends CustomEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        UserTfStepId {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getUserTfStepId();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setUserTfStepId((Number)value);
            }
        }
        ,
        UserTfId {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getUserTfId();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setUserTfId((Number)value);
            }
        }
        ,
        StepId {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getStepId();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setStepId((Number)value);
            }
        }
        ,
        IsCompleted {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getIsCompleted();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setIsCompleted((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getCreationDate();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        PortalUserTF {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getPortalUserTF();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setPortalUserTF((CustomEntityImpl)value);
            }
        }
        ,
        PortalUserTFStepDoc {
            public Object get(PortalUserTFStepImpl obj) {
                return obj.getPortalUserTFStepDoc();
            }

            public void put(PortalUserTFStepImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PortalUserTFStepImpl object);

        public abstract void put(PortalUserTFStepImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int USERTFSTEPID = AttributesEnum.UserTfStepId.index();
    public static final int USERTFID = AttributesEnum.UserTfId.index();
    public static final int STEPID = AttributesEnum.StepId.index();
    public static final int ISCOMPLETED = AttributesEnum.IsCompleted.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int PORTALUSERTF = AttributesEnum.PortalUserTF.index();
    public static final int PORTALUSERTFSTEPDOC = AttributesEnum.PortalUserTFStepDoc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PortalUserTFStepImpl() {
    }

    /**
     * Gets the attribute value for UserTfStepId, using the alias name UserTfStepId.
     * @return the UserTfStepId
     */
    public Number getUserTfStepId() {
        return (Number)getAttributeInternal(USERTFSTEPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserTfStepId.
     * @param value value to set the UserTfStepId
     */
    public void setUserTfStepId(Number value) {
        setAttributeInternal(USERTFSTEPID, value);
    }

    /**
     * Gets the attribute value for UserTfId, using the alias name UserTfId.
     * @return the UserTfId
     */
    public Number getUserTfId() {
        return (Number)getAttributeInternal(USERTFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserTfId.
     * @param value value to set the UserTfId
     */
    public void setUserTfId(Number value) {
        setAttributeInternal(USERTFID, value);
    }

    /**
     * Gets the attribute value for StepId, using the alias name StepId.
     * @return the StepId
     */
    public Number getStepId() {
        return (Number)getAttributeInternal(STEPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepId.
     * @param value value to set the StepId
     */
    public void setStepId(Number value) {
        setAttributeInternal(STEPID, value);
    }

    /**
     * Gets the attribute value for IsCompleted, using the alias name IsCompleted.
     * @return the IsCompleted
     */
    public String getIsCompleted() {
        return (String)getAttributeInternal(ISCOMPLETED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsCompleted.
     * @param value value to set the IsCompleted
     */
    public void setIsCompleted(String value) {
        setAttributeInternal(ISCOMPLETED, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity au.com.entitysolutions.taskflows.model.CustomEntityImpl.
     */
    public CustomEntityImpl getPortalUserTF() {
        return (CustomEntityImpl)getAttributeInternal(PORTALUSERTF);
    }

    /**
     * Sets <code>value</code> as the associated entity au.com.entitysolutions.taskflows.model.CustomEntityImpl.
     */
    public void setPortalUserTF(CustomEntityImpl value) {
        setAttributeInternal(PORTALUSERTF, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPortalUserTFStepDoc() {
        return (RowIterator)getAttributeInternal(PORTALUSERTFSTEPDOC);
    }

    /**
     * @param userTfStepId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number userTfStepId) {
        return new Key(new Object[]{userTfStepId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("au.com.entitysolutions.taskflows.train.model.PortalUserTFStep");
        }
        return mDefinitionObject;
    }
}
