package au.com.entitysolutions.taskflows.train.model;

import au.com.entitysolutions.taskflows.system.model.PortalCommonAppModuleImpl;


import au.com.entitysolutions.taskflows.train.model.common.TrainAppModule;

import java.util.logging.Logger;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.VariableValueManager;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 11:02:48 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrainAppModuleImpl extends PortalCommonAppModuleImpl implements TrainAppModule {

    private static final String SOURCE_CLASS = TrainAppModuleImpl.class.getCanonicalName();
    private static final Logger LOGGER = Logger.getLogger(SOURCE_CLASS);    
    
    /**
     * This is the default constructor (do not remove).
     */
    public TrainAppModuleImpl() {
    }

    /**
     * Container's getter for PortalUserTaskFlowsView.
     * @return PortalUserTaskFlowsView
     */
    public ViewObjectImpl getPortalUserTaskFlowsView() {
        return (ViewObjectImpl)findViewObject("PortalUserTaskFlowsView");
    }

    /**
     * Container's getter for PortalUserTFView.
     * @return PortalUserTFView
     */
    public ViewObjectImpl getPortalUserTFView() {
        return (ViewObjectImpl)findViewObject("PortalUserTFView");
    }
    
    /**
     * Start taskflow
     * @param userTFId
     */
    public void startTaskflow(String userTFId, String userName, String ipAddress) {
        LOGGER.entering(SOURCE_CLASS, "startTaskflow");
        LOGGER.finest("User TF Id:" + userTFId);
        ViewObjectImpl userTFView = this.getPortalUserTFView();
        VariableValueManager valMgr = userTFView.ensureVariableManager();
        valMgr.setVariableValue("p_user_tf_id", userTFId);
        userTFView.executeQuery();
        Row firstRow = userTFView.first();
        if(firstRow != null) {
            LOGGER.finest("Found UserTF row");
            firstRow.setAttribute("Status", "P"); //P indicates that the taskflow has been started by the user.
            this.auditUserAction("TASKFLOW STARTED: " + userTFId, userName, ipAddress );
        }
        else {
            throw new JboException("User Taskflow was not found");
        }
        LOGGER.exiting(SOURCE_CLASS, "startTaskflow");
    }

    /**
     * Container's getter for PortalUserTaskFlowsView1.
     * @return PortalUserTaskFlowsView1
     */
    public ViewObjectImpl getPortalUserTaskFlowsView1() {
        return (ViewObjectImpl)findViewObject("PortalUserTaskFlowsView1");
    }
}
