package au.com.entitysolutions.taskflows.payslips.model;

import au.com.entitysolutions.taskflows.payslips.model.common.PayslipsAppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 20 13:13:17 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PayslipsAppModuleImpl extends ApplicationModuleImpl implements PayslipsAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public PayslipsAppModuleImpl() {
    }

    /**
     * Container's getter for PaylsipsView1.
     * @return PaylsipsView1
     */
    public ViewObjectImpl getPaylsipsView1() {
        return (ViewObjectImpl)findViewObject("PaylsipsView1");
    }    
}
