package au.com.entitysolutions.taskflows.train.signup.model.common;

import au.com.entitysolutions.taskflows.train.model.common.CommonTrainTFAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 13:09:54 EST 2011
// ---------------------------------------------------------------------
public interface IProSignUpTrainAppModule extends CommonTrainTFAppModule {
    void createEmptySecondaryBankRecords();

    void resetPrimaryAccountPriority();


    void resetSuperDetails();

    void resetSuperFundType();

    void completeTaskFlow(String userTFId, String welcomeStepName,
                          String reviewStepName);

    void setICContractLookup();
}
