package au.com.entitysolutions.taskflows.hr.person.model;

import au.com.entitysolutions.taskflows.model.CustomEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 23 13:41:38 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HpPersonDImpl extends CustomEntityImpl {
  private static EntityDefImpl mDefinitionObject;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    PersonId {
      public Object get(HpPersonDImpl obj) {
        return obj.getPersonId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPersonId((Number)value);
      }
    }
    ,
    FromDate {
      public Object get(HpPersonDImpl obj) {
        return obj.getFromDate();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setFromDate((Date)value);
      }
    }
    ,
    ToDate {
      public Object get(HpPersonDImpl obj) {
        return obj.getToDate();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setToDate((Date)value);
      }
    }
    ,
    PersonNumber {
      public Object get(HpPersonDImpl obj) {
        return obj.getPersonNumber();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPersonNumber((String)value);
      }
    }
    ,
    BusinessGroupId {
      public Object get(HpPersonDImpl obj) {
        return obj.getBusinessGroupId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setBusinessGroupId((Number)value);
      }
    }
    ,
    FirstName {
      public Object get(HpPersonDImpl obj) {
        return obj.getFirstName();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setFirstName((String)value);
      }
    }
    ,
    MiddleName {
      public Object get(HpPersonDImpl obj) {
        return obj.getMiddleName();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setMiddleName((String)value);
      }
    }
    ,
    PersonType {
      public Object get(HpPersonDImpl obj) {
        return obj.getPersonType();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPersonType((String)value);
      }
    }
    ,
    Prefix {
      public Object get(HpPersonDImpl obj) {
        return obj.getPrefix();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPrefix((String)value);
      }
    }
    ,
    Surname {
      public Object get(HpPersonDImpl obj) {
        return obj.getSurname();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setSurname((String)value);
      }
    }
    ,
    PreferredName {
      public Object get(HpPersonDImpl obj) {
        return obj.getPreferredName();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPreferredName((String)value);
      }
    }
    ,
    FullName {
      public Object get(HpPersonDImpl obj) {
        return obj.getFullName();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setFullName((String)value);
      }
    }
    ,
    DateOfBirth {
      public Object get(HpPersonDImpl obj) {
        return obj.getDateOfBirth();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setDateOfBirth((Date)value);
      }
    }
    ,
    Gender {
      public Object get(HpPersonDImpl obj) {
        return obj.getGender();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setGender((String)value);
      }
    }
    ,
    FirstContact {
      public Object get(HpPersonDImpl obj) {
        return obj.getFirstContact();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setFirstContact((Date)value);
      }
    }
    ,
    PrimaryPersonTypeId {
      public Object get(HpPersonDImpl obj) {
        return obj.getPrimaryPersonTypeId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPrimaryPersonTypeId((Number)value);
      }
    }
    ,
    EmploymentCompanyOrgId {
      public Object get(HpPersonDImpl obj) {
        return obj.getEmploymentCompanyOrgId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setEmploymentCompanyOrgId((Number)value);
      }
    }
    ,
    ReferralId {
      public Object get(HpPersonDImpl obj) {
        return obj.getReferralId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setReferralId((Number)value);
      }
    }
    ,
    ReferralOrganisationId {
      public Object get(HpPersonDImpl obj) {
        return obj.getReferralOrganisationId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setReferralOrganisationId((Number)value);
      }
    }
    ,
    MemberSince {
      public Object get(HpPersonDImpl obj) {
        return obj.getMemberSince();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setMemberSince((Date)value);
      }
    }
    ,
    PersonalCommentId {
      public Object get(HpPersonDImpl obj) {
        return obj.getPersonalCommentId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPersonalCommentId((Number)value);
      }
    }
    ,
    ServiceStatus {
      public Object get(HpPersonDImpl obj) {
        return obj.getServiceStatus();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setServiceStatus((String)value);
      }
    }
    ,
    FirstAssignmentDate {
      public Object get(HpPersonDImpl obj) {
        return obj.getFirstAssignmentDate();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setFirstAssignmentDate((Date)value);
      }
    }
    ,
    ContractDaysWithEcms {
      public Object get(HpPersonDImpl obj) {
        return obj.getContractDaysWithEcms();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setContractDaysWithEcms((String)value);
      }
    }
    ,
    Function1 {
      public Object get(HpPersonDImpl obj) {
        return obj.getFunction1();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setFunction1((String)value);
      }
    }
    ,
    Skills {
      public Object get(HpPersonDImpl obj) {
        return obj.getSkills();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setSkills((String)value);
      }
    }
    ,
    EcmsAccountMgrId {
      public Object get(HpPersonDImpl obj) {
        return obj.getEcmsAccountMgrId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setEcmsAccountMgrId((Number)value);
      }
    }
    ,
    EcmsCsConsultantId {
      public Object get(HpPersonDImpl obj) {
        return obj.getEcmsCsConsultantId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setEcmsCsConsultantId((Number)value);
      }
    }
    ,
    EcmsPayrollConsultantId {
      public Object get(HpPersonDImpl obj) {
        return obj.getEcmsPayrollConsultantId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setEcmsPayrollConsultantId((String)value);
      }
    }
    ,
    ResignationDate {
      public Object get(HpPersonDImpl obj) {
        return obj.getResignationDate();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setResignationDate((Date)value);
      }
    }
    ,
    ResignationReason {
      public Object get(HpPersonDImpl obj) {
        return obj.getResignationReason();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setResignationReason((String)value);
      }
    }
    ,
    ResignationCommentId {
      public Object get(HpPersonDImpl obj) {
        return obj.getResignationCommentId();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setResignationCommentId((Number)value);
      }
    }
    ,
    PreviousEmploymentModel {
      public Object get(HpPersonDImpl obj) {
        return obj.getPreviousEmploymentModel();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPreviousEmploymentModel((String)value);
      }
    }
    ,
    ServiceType {
      public Object get(HpPersonDImpl obj) {
        return obj.getServiceType();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setServiceType((String)value);
      }
    }
    ,
    EmploymentType {
      public Object get(HpPersonDImpl obj) {
        return obj.getEmploymentType();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setEmploymentType((String)value);
      }
    }
    ,
    Attribute3 {
      public Object get(HpPersonDImpl obj) {
        return obj.getAttribute3();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setAttribute3((String)value);
      }
    }
    ,
    Attribute4 {
      public Object get(HpPersonDImpl obj) {
        return obj.getAttribute4();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setAttribute4((String)value);
      }
    }
    ,
    Attribute5 {
      public Object get(HpPersonDImpl obj) {
        return obj.getAttribute5();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setAttribute5((String)value);
      }
    }
    ,
    Attribute6 {
      public Object get(HpPersonDImpl obj) {
        return obj.getAttribute6();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setAttribute6((String)value);
      }
    }
    ,
    Attribute7 {
      public Object get(HpPersonDImpl obj) {
        return obj.getAttribute7();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setAttribute7((String)value);
      }
    }
    ,
    Attribute8 {
      public Object get(HpPersonDImpl obj) {
        return obj.getAttribute8();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setAttribute8((String)value);
      }
    }
    ,
    CustomerSupport {
      public Object get(HpPersonDImpl obj) {
        return obj.getCustomerSupport();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setCustomerSupport((Number)value);
      }
    }
    ,
    LafhaLeaseExpiry {
      public Object get(HpPersonDImpl obj) {
        return obj.getLafhaLeaseExpiry();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setLafhaLeaseExpiry((Date)value);
      }
    }
    ,
    CreatedBy {
      public Object get(HpPersonDImpl obj) {
        return obj.getCreatedBy();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setCreatedBy((Number)value);
      }
    }
    ,
    CreationDate {
      public Object get(HpPersonDImpl obj) {
        return obj.getCreationDate();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setCreationDate((Date)value);
      }
    }
    ,
    LastUpdateDate {
      public Object get(HpPersonDImpl obj) {
        return obj.getLastUpdateDate();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setLastUpdateDate((Date)value);
      }
    }
    ,
    LastUpdatedBy {
      public Object get(HpPersonDImpl obj) {
        return obj.getLastUpdatedBy();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setLastUpdatedBy((Number)value);
      }
    }
    ,
    MaritalStatus {
      public Object get(HpPersonDImpl obj) {
        return obj.getMaritalStatus();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setMaritalStatus((String)value);
      }
    }
    ,
    Title {
      public Object get(HpPersonDImpl obj) {
        return obj.getTitle();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setTitle((String)value);
      }
    }
    ,
    LafhaEligible {
      public Object get(HpPersonDImpl obj) {
        return obj.getLafhaEligible();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setLafhaEligible((String)value);
      }
    }
    ,
    LafhaAmount {
      public Object get(HpPersonDImpl obj) {
        return obj.getLafhaAmount();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setLafhaAmount((Number)value);
      }
    }
    ,
    ReferenceNo {
      public Object get(HpPersonDImpl obj) {
        return obj.getReferenceNo();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setReferenceNo((String)value);
      }
    }
    ,
    Preferred {
      public Object get(HpPersonDImpl obj) {
        return obj.getPreferred();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPreferred((String)value);
      }
    }
    ,
    PayrollNotes {
      public Object get(HpPersonDImpl obj) {
        return obj.getPayrollNotes();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPayrollNotes((String)value);
      }
    }
    ,
    PayslipEmail {
      public Object get(HpPersonDImpl obj) {
        return obj.getPayslipEmail();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setPayslipEmail((String)value);
      }
    }
    ,
    ReferenceNo2 {
      public Object get(HpPersonDImpl obj) {
        return obj.getReferenceNo2();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setReferenceNo2((String)value);
      }
    }
    ,
    ReferenceNo3 {
      public Object get(HpPersonDImpl obj) {
        return obj.getReferenceNo3();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setReferenceNo3((String)value);
      }
    }
    ,
    GtmStage {
      public Object get(HpPersonDImpl obj) {
        return obj.getGtmStage();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setGtmStage((String)value);
      }
    }
    ,
    GtmProfile {
      public Object get(HpPersonDImpl obj) {
        return obj.getGtmProfile();
      }

      public void put(HpPersonDImpl obj, Object value) {
        obj.setGtmProfile((String)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(HpPersonDImpl object);

    public abstract void put(HpPersonDImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int PERSONID = AttributesEnum.PersonId.index();
  public static final int FROMDATE = AttributesEnum.FromDate.index();
  public static final int TODATE = AttributesEnum.ToDate.index();
  public static final int PERSONNUMBER = AttributesEnum.PersonNumber.index();
  public static final int BUSINESSGROUPID = AttributesEnum.BusinessGroupId.index();
  public static final int FIRSTNAME = AttributesEnum.FirstName.index();
  public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
  public static final int PERSONTYPE = AttributesEnum.PersonType.index();
  public static final int PREFIX = AttributesEnum.Prefix.index();
  public static final int SURNAME = AttributesEnum.Surname.index();
  public static final int PREFERREDNAME = AttributesEnum.PreferredName.index();
  public static final int FULLNAME = AttributesEnum.FullName.index();
  public static final int DATEOFBIRTH = AttributesEnum.DateOfBirth.index();
  public static final int GENDER = AttributesEnum.Gender.index();
  public static final int FIRSTCONTACT = AttributesEnum.FirstContact.index();
  public static final int PRIMARYPERSONTYPEID = AttributesEnum.PrimaryPersonTypeId.index();
  public static final int EMPLOYMENTCOMPANYORGID = AttributesEnum.EmploymentCompanyOrgId.index();
  public static final int REFERRALID = AttributesEnum.ReferralId.index();
  public static final int REFERRALORGANISATIONID = AttributesEnum.ReferralOrganisationId.index();
  public static final int MEMBERSINCE = AttributesEnum.MemberSince.index();
  public static final int PERSONALCOMMENTID = AttributesEnum.PersonalCommentId.index();
  public static final int SERVICESTATUS = AttributesEnum.ServiceStatus.index();
  public static final int FIRSTASSIGNMENTDATE = AttributesEnum.FirstAssignmentDate.index();
  public static final int CONTRACTDAYSWITHECMS = AttributesEnum.ContractDaysWithEcms.index();
  public static final int FUNCTION1 = AttributesEnum.Function1.index();
  public static final int SKILLS = AttributesEnum.Skills.index();
  public static final int ECMSACCOUNTMGRID = AttributesEnum.EcmsAccountMgrId.index();
  public static final int ECMSCSCONSULTANTID = AttributesEnum.EcmsCsConsultantId.index();
  public static final int ECMSPAYROLLCONSULTANTID = AttributesEnum.EcmsPayrollConsultantId.index();
  public static final int RESIGNATIONDATE = AttributesEnum.ResignationDate.index();
  public static final int RESIGNATIONREASON = AttributesEnum.ResignationReason.index();
  public static final int RESIGNATIONCOMMENTID = AttributesEnum.ResignationCommentId.index();
  public static final int PREVIOUSEMPLOYMENTMODEL = AttributesEnum.PreviousEmploymentModel.index();
  public static final int SERVICETYPE = AttributesEnum.ServiceType.index();
  public static final int EMPLOYMENTTYPE = AttributesEnum.EmploymentType.index();
  public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
  public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
  public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
  public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
  public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
  public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
  public static final int CUSTOMERSUPPORT = AttributesEnum.CustomerSupport.index();
  public static final int LAFHALEASEEXPIRY = AttributesEnum.LafhaLeaseExpiry.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
  public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
  public static final int MARITALSTATUS = AttributesEnum.MaritalStatus.index();
  public static final int TITLE = AttributesEnum.Title.index();
  public static final int LAFHAELIGIBLE = AttributesEnum.LafhaEligible.index();
  public static final int LAFHAAMOUNT = AttributesEnum.LafhaAmount.index();
  public static final int REFERENCENO = AttributesEnum.ReferenceNo.index();
  public static final int PREFERRED = AttributesEnum.Preferred.index();
  public static final int PAYROLLNOTES = AttributesEnum.PayrollNotes.index();
  public static final int PAYSLIPEMAIL = AttributesEnum.PayslipEmail.index();
  public static final int REFERENCENO2 = AttributesEnum.ReferenceNo2.index();
  public static final int REFERENCENO3 = AttributesEnum.ReferenceNo3.index();
  public static final int GTMSTAGE = AttributesEnum.GtmStage.index();
  public static final int GTMPROFILE = AttributesEnum.GtmProfile.index();

  /**
   * This is the default constructor (do not remove).
   */
  public HpPersonDImpl() {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    if (mDefinitionObject == null) {
      mDefinitionObject = EntityDefImpl.findDefObject("au.com.entitysolutions.taskflows.hr.person.model.HpPersonD");
    }
    return mDefinitionObject;
  }

  /**
   * Gets the attribute value for PersonId, using the alias name PersonId.
   * @return the PersonId
   */
  public Number getPersonId() {
    return (Number)getAttributeInternal(PERSONID);
  }

  /**
   * Sets <code>value</code> as the attribute value for PersonId.
   * @param value value to set the PersonId
   */
  public void setPersonId(Number value) {
    setAttributeInternal(PERSONID, value);
  }

  /**
   * Gets the attribute value for FromDate, using the alias name FromDate.
   * @return the FromDate
   */
  public Date getFromDate() {
    return (Date)getAttributeInternal(FROMDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for FromDate.
   * @param value value to set the FromDate
   */
  public void setFromDate(Date value) {
    setAttributeInternal(FROMDATE, value);
  }

  /**
   * Gets the attribute value for ToDate, using the alias name ToDate.
   * @return the ToDate
   */
  public Date getToDate() {
    return (Date)getAttributeInternal(TODATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ToDate.
   * @param value value to set the ToDate
   */
  public void setToDate(Date value) {
    setAttributeInternal(TODATE, value);
  }

  /**
   * Gets the attribute value for PersonNumber, using the alias name PersonNumber.
   * @return the PersonNumber
   */
  public String getPersonNumber() {
    return (String)getAttributeInternal(PERSONNUMBER);
  }

  /**
   * Sets <code>value</code> as the attribute value for PersonNumber.
   * @param value value to set the PersonNumber
   */
  public void setPersonNumber(String value) {
    setAttributeInternal(PERSONNUMBER, value);
  }

  /**
   * Gets the attribute value for BusinessGroupId, using the alias name BusinessGroupId.
   * @return the BusinessGroupId
   */
  public Number getBusinessGroupId() {
    return (Number)getAttributeInternal(BUSINESSGROUPID);
  }

  /**
   * Sets <code>value</code> as the attribute value for BusinessGroupId.
   * @param value value to set the BusinessGroupId
   */
  public void setBusinessGroupId(Number value) {
    setAttributeInternal(BUSINESSGROUPID, value);
  }

  /**
   * Gets the attribute value for FirstName, using the alias name FirstName.
   * @return the FirstName
   */
  public String getFirstName() {
    return (String)getAttributeInternal(FIRSTNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for FirstName.
   * @param value value to set the FirstName
   */
  public void setFirstName(String value) {
    setAttributeInternal(FIRSTNAME, value);
  }

  /**
   * Gets the attribute value for MiddleName, using the alias name MiddleName.
   * @return the MiddleName
   */
  public String getMiddleName() {
    return (String)getAttributeInternal(MIDDLENAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for MiddleName.
   * @param value value to set the MiddleName
   */
  public void setMiddleName(String value) {
    setAttributeInternal(MIDDLENAME, value);
  }

  /**
   * Gets the attribute value for PersonType, using the alias name PersonType.
   * @return the PersonType
   */
  public String getPersonType() {
    return (String)getAttributeInternal(PERSONTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for PersonType.
   * @param value value to set the PersonType
   */
  public void setPersonType(String value) {
    setAttributeInternal(PERSONTYPE, value);
  }

  /**
   * Gets the attribute value for Prefix, using the alias name Prefix.
   * @return the Prefix
   */
  public String getPrefix() {
    return (String)getAttributeInternal(PREFIX);
  }

  /**
   * Sets <code>value</code> as the attribute value for Prefix.
   * @param value value to set the Prefix
   */
  public void setPrefix(String value) {
    setAttributeInternal(PREFIX, value);
  }

  /**
   * Gets the attribute value for Surname, using the alias name Surname.
   * @return the Surname
   */
  public String getSurname() {
    return (String)getAttributeInternal(SURNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for Surname.
   * @param value value to set the Surname
   */
  public void setSurname(String value) {
    setAttributeInternal(SURNAME, value);
  }

  /**
   * Gets the attribute value for PreferredName, using the alias name PreferredName.
   * @return the PreferredName
   */
  public String getPreferredName() {
    return (String)getAttributeInternal(PREFERREDNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for PreferredName.
   * @param value value to set the PreferredName
   */
  public void setPreferredName(String value) {
    setAttributeInternal(PREFERREDNAME, value);
  }

  /**
   * Gets the attribute value for FullName, using the alias name FullName.
   * @return the FullName
   */
  public String getFullName() {
    return (String)getAttributeInternal(FULLNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for FullName.
   * @param value value to set the FullName
   */
  public void setFullName(String value) {
    setAttributeInternal(FULLNAME, value);
  }

  /**
   * Gets the attribute value for DateOfBirth, using the alias name DateOfBirth.
   * @return the DateOfBirth
   */
  public Date getDateOfBirth() {
    return (Date)getAttributeInternal(DATEOFBIRTH);
  }

  /**
   * Sets <code>value</code> as the attribute value for DateOfBirth.
   * @param value value to set the DateOfBirth
   */
  public void setDateOfBirth(Date value) {
    setAttributeInternal(DATEOFBIRTH, value);
  }

  /**
   * Gets the attribute value for Gender, using the alias name Gender.
   * @return the Gender
   */
  public String getGender() {
    return (String)getAttributeInternal(GENDER);
  }

  /**
   * Sets <code>value</code> as the attribute value for Gender.
   * @param value value to set the Gender
   */
  public void setGender(String value) {
    setAttributeInternal(GENDER, value);
  }

  /**
   * Gets the attribute value for FirstContact, using the alias name FirstContact.
   * @return the FirstContact
   */
  public Date getFirstContact() {
    return (Date)getAttributeInternal(FIRSTCONTACT);
  }

  /**
   * Sets <code>value</code> as the attribute value for FirstContact.
   * @param value value to set the FirstContact
   */
  public void setFirstContact(Date value) {
    setAttributeInternal(FIRSTCONTACT, value);
  }

  /**
   * Gets the attribute value for PrimaryPersonTypeId, using the alias name PrimaryPersonTypeId.
   * @return the PrimaryPersonTypeId
   */
  public Number getPrimaryPersonTypeId() {
    return (Number)getAttributeInternal(PRIMARYPERSONTYPEID);
  }

  /**
   * Sets <code>value</code> as the attribute value for PrimaryPersonTypeId.
   * @param value value to set the PrimaryPersonTypeId
   */
  public void setPrimaryPersonTypeId(Number value) {
    setAttributeInternal(PRIMARYPERSONTYPEID, value);
  }

  /**
   * Gets the attribute value for EmploymentCompanyOrgId, using the alias name EmploymentCompanyOrgId.
   * @return the EmploymentCompanyOrgId
   */
  public Number getEmploymentCompanyOrgId() {
    return (Number)getAttributeInternal(EMPLOYMENTCOMPANYORGID);
  }

  /**
   * Sets <code>value</code> as the attribute value for EmploymentCompanyOrgId.
   * @param value value to set the EmploymentCompanyOrgId
   */
  public void setEmploymentCompanyOrgId(Number value) {
    setAttributeInternal(EMPLOYMENTCOMPANYORGID, value);
  }

  /**
   * Gets the attribute value for ReferralId, using the alias name ReferralId.
   * @return the ReferralId
   */
  public Number getReferralId() {
    return (Number)getAttributeInternal(REFERRALID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ReferralId.
   * @param value value to set the ReferralId
   */
  public void setReferralId(Number value) {
    setAttributeInternal(REFERRALID, value);
  }

  /**
   * Gets the attribute value for ReferralOrganisationId, using the alias name ReferralOrganisationId.
   * @return the ReferralOrganisationId
   */
  public Number getReferralOrganisationId() {
    return (Number)getAttributeInternal(REFERRALORGANISATIONID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ReferralOrganisationId.
   * @param value value to set the ReferralOrganisationId
   */
  public void setReferralOrganisationId(Number value) {
    setAttributeInternal(REFERRALORGANISATIONID, value);
  }

  /**
   * Gets the attribute value for MemberSince, using the alias name MemberSince.
   * @return the MemberSince
   */
  public Date getMemberSince() {
    return (Date)getAttributeInternal(MEMBERSINCE);
  }

  /**
   * Sets <code>value</code> as the attribute value for MemberSince.
   * @param value value to set the MemberSince
   */
  public void setMemberSince(Date value) {
    setAttributeInternal(MEMBERSINCE, value);
  }

  /**
   * Gets the attribute value for PersonalCommentId, using the alias name PersonalCommentId.
   * @return the PersonalCommentId
   */
  public Number getPersonalCommentId() {
    return (Number)getAttributeInternal(PERSONALCOMMENTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for PersonalCommentId.
   * @param value value to set the PersonalCommentId
   */
  public void setPersonalCommentId(Number value) {
    setAttributeInternal(PERSONALCOMMENTID, value);
  }

  /**
   * Gets the attribute value for ServiceStatus, using the alias name ServiceStatus.
   * @return the ServiceStatus
   */
  public String getServiceStatus() {
    return (String)getAttributeInternal(SERVICESTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for ServiceStatus.
   * @param value value to set the ServiceStatus
   */
  public void setServiceStatus(String value) {
    setAttributeInternal(SERVICESTATUS, value);
  }

  /**
   * Gets the attribute value for FirstAssignmentDate, using the alias name FirstAssignmentDate.
   * @return the FirstAssignmentDate
   */
  public Date getFirstAssignmentDate() {
    return (Date)getAttributeInternal(FIRSTASSIGNMENTDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for FirstAssignmentDate.
   * @param value value to set the FirstAssignmentDate
   */
  public void setFirstAssignmentDate(Date value) {
    setAttributeInternal(FIRSTASSIGNMENTDATE, value);
  }

  /**
   * Gets the attribute value for ContractDaysWithEcms, using the alias name ContractDaysWithEcms.
   * @return the ContractDaysWithEcms
   */
  public String getContractDaysWithEcms() {
    return (String)getAttributeInternal(CONTRACTDAYSWITHECMS);
  }

  /**
   * Sets <code>value</code> as the attribute value for ContractDaysWithEcms.
   * @param value value to set the ContractDaysWithEcms
   */
  public void setContractDaysWithEcms(String value) {
    setAttributeInternal(CONTRACTDAYSWITHECMS, value);
  }

  /**
   * Gets the attribute value for Function1, using the alias name Function1.
   * @return the Function1
   */
  public String getFunction1() {
    return (String)getAttributeInternal(FUNCTION1);
  }

  /**
   * Sets <code>value</code> as the attribute value for Function1.
   * @param value value to set the Function1
   */
  public void setFunction1(String value) {
    setAttributeInternal(FUNCTION1, value);
  }

  /**
   * Gets the attribute value for Skills, using the alias name Skills.
   * @return the Skills
   */
  public String getSkills() {
    return (String)getAttributeInternal(SKILLS);
  }

  /**
   * Sets <code>value</code> as the attribute value for Skills.
   * @param value value to set the Skills
   */
  public void setSkills(String value) {
    setAttributeInternal(SKILLS, value);
  }

  /**
   * Gets the attribute value for EcmsAccountMgrId, using the alias name EcmsAccountMgrId.
   * @return the EcmsAccountMgrId
   */
  public Number getEcmsAccountMgrId() {
    return (Number)getAttributeInternal(ECMSACCOUNTMGRID);
  }

  /**
   * Sets <code>value</code> as the attribute value for EcmsAccountMgrId.
   * @param value value to set the EcmsAccountMgrId
   */
  public void setEcmsAccountMgrId(Number value) {
    setAttributeInternal(ECMSACCOUNTMGRID, value);
  }

  /**
   * Gets the attribute value for EcmsCsConsultantId, using the alias name EcmsCsConsultantId.
   * @return the EcmsCsConsultantId
   */
  public Number getEcmsCsConsultantId() {
    return (Number)getAttributeInternal(ECMSCSCONSULTANTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for EcmsCsConsultantId.
   * @param value value to set the EcmsCsConsultantId
   */
  public void setEcmsCsConsultantId(Number value) {
    setAttributeInternal(ECMSCSCONSULTANTID, value);
  }

  /**
   * Gets the attribute value for EcmsPayrollConsultantId, using the alias name EcmsPayrollConsultantId.
   * @return the EcmsPayrollConsultantId
   */
  public String getEcmsPayrollConsultantId() {
    return (String)getAttributeInternal(ECMSPAYROLLCONSULTANTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for EcmsPayrollConsultantId.
   * @param value value to set the EcmsPayrollConsultantId
   */
  public void setEcmsPayrollConsultantId(String value) {
    setAttributeInternal(ECMSPAYROLLCONSULTANTID, value);
  }

  /**
   * Gets the attribute value for ResignationDate, using the alias name ResignationDate.
   * @return the ResignationDate
   */
  public Date getResignationDate() {
    return (Date)getAttributeInternal(RESIGNATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ResignationDate.
   * @param value value to set the ResignationDate
   */
  public void setResignationDate(Date value) {
    setAttributeInternal(RESIGNATIONDATE, value);
  }

  /**
   * Gets the attribute value for ResignationReason, using the alias name ResignationReason.
   * @return the ResignationReason
   */
  public String getResignationReason() {
    return (String)getAttributeInternal(RESIGNATIONREASON);
  }

  /**
   * Sets <code>value</code> as the attribute value for ResignationReason.
   * @param value value to set the ResignationReason
   */
  public void setResignationReason(String value) {
    setAttributeInternal(RESIGNATIONREASON, value);
  }

  /**
   * Gets the attribute value for ResignationCommentId, using the alias name ResignationCommentId.
   * @return the ResignationCommentId
   */
  public Number getResignationCommentId() {
    return (Number)getAttributeInternal(RESIGNATIONCOMMENTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for ResignationCommentId.
   * @param value value to set the ResignationCommentId
   */
  public void setResignationCommentId(Number value) {
    setAttributeInternal(RESIGNATIONCOMMENTID, value);
  }

  /**
   * Gets the attribute value for PreviousEmploymentModel, using the alias name PreviousEmploymentModel.
   * @return the PreviousEmploymentModel
   */
  public String getPreviousEmploymentModel() {
    return (String)getAttributeInternal(PREVIOUSEMPLOYMENTMODEL);
  }

  /**
   * Sets <code>value</code> as the attribute value for PreviousEmploymentModel.
   * @param value value to set the PreviousEmploymentModel
   */
  public void setPreviousEmploymentModel(String value) {
    setAttributeInternal(PREVIOUSEMPLOYMENTMODEL, value);
  }

  /**
   * Gets the attribute value for ServiceType, using the alias name ServiceType.
   * @return the ServiceType
   */
  public String getServiceType() {
    return (String)getAttributeInternal(SERVICETYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ServiceType.
   * @param value value to set the ServiceType
   */
  public void setServiceType(String value) {
    setAttributeInternal(SERVICETYPE, value);
  }

  /**
   * Gets the attribute value for EmploymentType, using the alias name EmploymentType.
   * @return the EmploymentType
   */
  public String getEmploymentType() {
    return (String)getAttributeInternal(EMPLOYMENTTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for EmploymentType.
   * @param value value to set the EmploymentType
   */
  public void setEmploymentType(String value) {
    setAttributeInternal(EMPLOYMENTTYPE, value);
  }

  /**
   * Gets the attribute value for Attribute3, using the alias name Attribute3.
   * @return the Attribute3
   */
  public String getAttribute3() {
    return (String)getAttributeInternal(ATTRIBUTE3);
  }

  /**
   * Sets <code>value</code> as the attribute value for Attribute3.
   * @param value value to set the Attribute3
   */
  public void setAttribute3(String value) {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**
   * Gets the attribute value for Attribute4, using the alias name Attribute4.
   * @return the Attribute4
   */
  public String getAttribute4() {
    return (String)getAttributeInternal(ATTRIBUTE4);
  }

  /**
   * Sets <code>value</code> as the attribute value for Attribute4.
   * @param value value to set the Attribute4
   */
  public void setAttribute4(String value) {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**
   * Gets the attribute value for Attribute5, using the alias name Attribute5.
   * @return the Attribute5
   */
  public String getAttribute5() {
    return (String)getAttributeInternal(ATTRIBUTE5);
  }

  /**
   * Sets <code>value</code> as the attribute value for Attribute5.
   * @param value value to set the Attribute5
   */
  public void setAttribute5(String value) {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**
   * Gets the attribute value for Attribute6, using the alias name Attribute6.
   * @return the Attribute6
   */
  public String getAttribute6() {
    return (String)getAttributeInternal(ATTRIBUTE6);
  }

  /**
   * Sets <code>value</code> as the attribute value for Attribute6.
   * @param value value to set the Attribute6
   */
  public void setAttribute6(String value) {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**
   * Gets the attribute value for Attribute7, using the alias name Attribute7.
   * @return the Attribute7
   */
  public String getAttribute7() {
    return (String)getAttributeInternal(ATTRIBUTE7);
  }

  /**
   * Sets <code>value</code> as the attribute value for Attribute7.
   * @param value value to set the Attribute7
   */
  public void setAttribute7(String value) {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**
   * Gets the attribute value for Attribute8, using the alias name Attribute8.
   * @return the Attribute8
   */
  public String getAttribute8() {
    return (String)getAttributeInternal(ATTRIBUTE8);
  }

  /**
   * Sets <code>value</code> as the attribute value for Attribute8.
   * @param value value to set the Attribute8
   */
  public void setAttribute8(String value) {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**
   * Gets the attribute value for CustomerSupport, using the alias name CustomerSupport.
   * @return the CustomerSupport
   */
  public Number getCustomerSupport() {
    return (Number)getAttributeInternal(CUSTOMERSUPPORT);
  }

  /**
   * Sets <code>value</code> as the attribute value for CustomerSupport.
   * @param value value to set the CustomerSupport
   */
  public void setCustomerSupport(Number value) {
    setAttributeInternal(CUSTOMERSUPPORT, value);
  }

  /**
   * Gets the attribute value for LafhaLeaseExpiry, using the alias name LafhaLeaseExpiry.
   * @return the LafhaLeaseExpiry
   */
  public Date getLafhaLeaseExpiry() {
    return (Date)getAttributeInternal(LAFHALEASEEXPIRY);
  }

  /**
   * Sets <code>value</code> as the attribute value for LafhaLeaseExpiry.
   * @param value value to set the LafhaLeaseExpiry
   */
  public void setLafhaLeaseExpiry(Date value) {
    setAttributeInternal(LAFHALEASEEXPIRY, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the CreatedBy
   */
  public Number getCreatedBy() {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(Number value) {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the CreationDate
   */
  public Date getCreationDate() {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Date value) {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
   * @return the LastUpdateDate
   */
  public Date getLastUpdateDate() {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for LastUpdateDate.
   * @param value value to set the LastUpdateDate
   */
  public void setLastUpdateDate(Date value) {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**
   * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
   * @return the LastUpdatedBy
   */
  public Number getLastUpdatedBy() {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for LastUpdatedBy.
   * @param value value to set the LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value) {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**
   * Gets the attribute value for MaritalStatus, using the alias name MaritalStatus.
   * @return the MaritalStatus
   */
  public String getMaritalStatus() {
    return (String)getAttributeInternal(MARITALSTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for MaritalStatus.
   * @param value value to set the MaritalStatus
   */
  public void setMaritalStatus(String value) {
    setAttributeInternal(MARITALSTATUS, value);
  }

  /**
   * Gets the attribute value for Title, using the alias name Title.
   * @return the Title
   */
  public String getTitle() {
    return (String)getAttributeInternal(TITLE);
  }

  /**
   * Sets <code>value</code> as the attribute value for Title.
   * @param value value to set the Title
   */
  public void setTitle(String value) {
    setAttributeInternal(TITLE, value);
  }

  /**
   * Gets the attribute value for LafhaEligible, using the alias name LafhaEligible.
   * @return the LafhaEligible
   */
  public String getLafhaEligible() {
    return (String)getAttributeInternal(LAFHAELIGIBLE);
  }

  /**
   * Sets <code>value</code> as the attribute value for LafhaEligible.
   * @param value value to set the LafhaEligible
   */
  public void setLafhaEligible(String value) {
    setAttributeInternal(LAFHAELIGIBLE, value);
  }

  /**
   * Gets the attribute value for LafhaAmount, using the alias name LafhaAmount.
   * @return the LafhaAmount
   */
  public Number getLafhaAmount() {
    return (Number)getAttributeInternal(LAFHAAMOUNT);
  }

  /**
   * Sets <code>value</code> as the attribute value for LafhaAmount.
   * @param value value to set the LafhaAmount
   */
  public void setLafhaAmount(Number value) {
    setAttributeInternal(LAFHAAMOUNT, value);
  }

  /**
   * Gets the attribute value for ReferenceNo, using the alias name ReferenceNo.
   * @return the ReferenceNo
   */
  public String getReferenceNo() {
    return (String)getAttributeInternal(REFERENCENO);
  }

  /**
   * Sets <code>value</code> as the attribute value for ReferenceNo.
   * @param value value to set the ReferenceNo
   */
  public void setReferenceNo(String value) {
    setAttributeInternal(REFERENCENO, value);
  }

  /**
   * Gets the attribute value for Preferred, using the alias name Preferred.
   * @return the Preferred
   */
  public String getPreferred() {
    return (String)getAttributeInternal(PREFERRED);
  }

  /**
   * Sets <code>value</code> as the attribute value for Preferred.
   * @param value value to set the Preferred
   */
  public void setPreferred(String value) {
    setAttributeInternal(PREFERRED, value);
  }

  /**
   * Gets the attribute value for PayrollNotes, using the alias name PayrollNotes.
   * @return the PayrollNotes
   */
  public String getPayrollNotes() {
    return (String)getAttributeInternal(PAYROLLNOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for PayrollNotes.
   * @param value value to set the PayrollNotes
   */
  public void setPayrollNotes(String value) {
    setAttributeInternal(PAYROLLNOTES, value);
  }

  /**
   * Gets the attribute value for PayslipEmail, using the alias name PayslipEmail.
   * @return the PayslipEmail
   */
  public String getPayslipEmail() {
    return (String)getAttributeInternal(PAYSLIPEMAIL);
  }

  /**
   * Sets <code>value</code> as the attribute value for PayslipEmail.
   * @param value value to set the PayslipEmail
   */
  public void setPayslipEmail(String value) {
    setAttributeInternal(PAYSLIPEMAIL, value);
  }

  /**
   * Gets the attribute value for ReferenceNo2, using the alias name ReferenceNo2.
   * @return the ReferenceNo2
   */
  public String getReferenceNo2() {
    return (String)getAttributeInternal(REFERENCENO2);
  }

  /**
   * Sets <code>value</code> as the attribute value for ReferenceNo2.
   * @param value value to set the ReferenceNo2
   */
  public void setReferenceNo2(String value) {
    setAttributeInternal(REFERENCENO2, value);
  }

  /**
   * Gets the attribute value for ReferenceNo3, using the alias name ReferenceNo3.
   * @return the ReferenceNo3
   */
  public String getReferenceNo3() {
    return (String)getAttributeInternal(REFERENCENO3);
  }

  /**
   * Sets <code>value</code> as the attribute value for ReferenceNo3.
   * @param value value to set the ReferenceNo3
   */
  public void setReferenceNo3(String value) {
    setAttributeInternal(REFERENCENO3, value);
  }

  /**
   * Gets the attribute value for GtmStage, using the alias name GtmStage.
   * @return the GtmStage
   */
  public String getGtmStage() {
    return (String)getAttributeInternal(GTMSTAGE);
  }

  /**
   * Sets <code>value</code> as the attribute value for GtmStage.
   * @param value value to set the GtmStage
   */
  public void setGtmStage(String value) {
    setAttributeInternal(GTMSTAGE, value);
  }

  /**
   * Gets the attribute value for GtmProfile, using the alias name GtmProfile.
   * @return the GtmProfile
   */
  public String getGtmProfile() {
    return (String)getAttributeInternal(GTMPROFILE);
  }

  /**
   * Sets <code>value</code> as the attribute value for GtmProfile.
   * @param value value to set the GtmProfile
   */
  public void setGtmProfile(String value) {
    setAttributeInternal(GTMPROFILE, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @param personId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Number personId) {
    return new Key(new Object[]{personId});
  }


}
