package au.com.entitysolutions.taskflows.payslips.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 20 13:42:07 EST 2012
// ---------------------------------------------------------------------
public interface PayslipsAppModule extends ApplicationModule {
}
