package au.com.entitysolutions.taskflows.payslips.model.client;

import au.com.entitysolutions.taskflows.payslips.model.common.PayslipsAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 20 13:42:07 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PayslipsAppModuleClient extends ApplicationModuleImpl implements PayslipsAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public PayslipsAppModuleClient() {
    }
   
}
